### ISSUE TITLE
 My App gets disconnected when load highcharter package 

### ISSUE THREAD

**Issue by namrouche993** [randy3k/shiny-cloudrun-demo#3]
i'm new in docker , and first Thank you for you work, it's the only docker project that works for me,
and also no problem is found when i install highcharter package in dockerfile

but in app.R file when i just add library(highcharter) , my app will be  deconnected

and here is the project link in github : https://github.com/namrouche993/template33

**Comment by randy3k** [comment]
The log file for google cloud run should contain some useful debug infomration? I remember that I had to increase the memory of an instance to make a shiny application work.

**Comment by namrouche993** [comment]
> The log file for google cloud run should contain some useful debug infomration? I remember that I had to increase the memory of an instance to make a shiny application work.

problem solving , thanks a lot
